import cover1 from "@/assets/covers/cover-1.jpg";
import cover2 from "@/assets/covers/cover-2.jpg";
import cover3 from "@/assets/covers/cover-3.jpg";
import cover4 from "@/assets/covers/cover-4.jpg";

export interface Beat {
  id: string;
  title: string;
  producer: string;
  genre: string;
  bpm: number;
  price: number;
  mood: string;
  coverUrl?: string;
  isExclusive?: boolean;
  duration: string;
  plays: number;
  tags: string[];
  description: string;
}

export const mockBeats: Beat[] = [
  {
    id: "1",
    title: "Midnight Drive",
    producer: "BEATVAULT",
    genre: "Trap",
    bpm: 140,
    price: 29.99,
    mood: "Dark",
    isExclusive: true,
    coverUrl: cover1,
    duration: "3:45",
    plays: 12400,
    tags: ["Dark", "808", "Melodic"],
    description: "Hard-hitting trap banger with deep 808s and eerie synth melodies. Perfect for late-night sessions.",
  },
  {
    id: "2",
    title: "City Lights",
    producer: "BEATVAULT",
    genre: "Lo-Fi",
    bpm: 85,
    price: 19.99,
    mood: "Chill",
    coverUrl: cover2,
    duration: "2:58",
    plays: 8700,
    tags: ["Chill", "Study", "Jazzy"],
    description: "Smooth lo-fi vibes with warm vinyl crackles and jazzy chord progressions.",
  },
  {
    id: "3",
    title: "War Ready",
    producer: "BEATVAULT",
    genre: "Drill",
    bpm: 145,
    price: 34.99,
    mood: "Aggressive",
    coverUrl: cover3,
    duration: "3:12",
    plays: 19200,
    tags: ["Drill", "Dark", "Aggressive"],
    description: "UK/Chicago drill hybrid with sliding 808s and menacing orchestral strings.",
  },
  {
    id: "4",
    title: "Purple Haze",
    producer: "BEATVAULT",
    genre: "Hip-Hop",
    bpm: 92,
    price: 24.99,
    mood: "Melodic",
    coverUrl: cover4,
    duration: "3:28",
    plays: 6100,
    tags: ["Melodic", "Boom Bap", "Classic"],
    description: "Classic boom bap with a modern twist. Soulful samples over hard-hitting drums.",
  },
  {
    id: "5",
    title: "Neon Dreams",
    producer: "BEATVAULT",
    genre: "R&B",
    bpm: 110,
    price: 29.99,
    mood: "Emotional",
    isExclusive: true,
    coverUrl: cover1,
    duration: "3:55",
    plays: 9800,
    tags: ["Emotional", "Romantic", "Smooth"],
    description: "Silky R&B production with lush chords and intimate atmosphere.",
  },
  {
    id: "6",
    title: "Thunder",
    producer: "BEATVAULT",
    genre: "Cinematic",
    bpm: 120,
    price: 49.99,
    mood: "Energetic",
    isExclusive: true,
    coverUrl: cover3,
    duration: "4:10",
    plays: 15600,
    tags: ["Epic", "Orchestral", "Cinematic"],
    description: "Massive cinematic score with orchestral swells and thunderous percussion.",
  },
  {
    id: "7",
    title: "Smooth Operator",
    producer: "BEATVAULT",
    genre: "R&B",
    bpm: 95,
    price: 22.99,
    mood: "Chill",
    coverUrl: cover2,
    duration: "3:20",
    plays: 4400,
    tags: ["Smooth", "Neo-Soul", "Chill"],
    description: "Neo-soul influenced R&B with warm bass lines and silky keys.",
  },
  {
    id: "8",
    title: "Gunsmoke",
    producer: "BEATVAULT",
    genre: "Trap",
    bpm: 150,
    price: 27.99,
    mood: "Dark",
    coverUrl: cover4,
    duration: "3:02",
    plays: 22100,
    tags: ["Hard", "Dark", "Street"],
    description: "Raw street trap energy with heavy 808s and menacing synths.",
  },
  {
    id: "9",
    title: "Soul Searching",
    producer: "BEATVAULT",
    genre: "Hip-Hop",
    bpm: 88,
    price: 26.99,
    mood: "Melodic",
    coverUrl: cover1,
    duration: "3:38",
    plays: 7300,
    tags: ["Soulful", "Deep", "Conscious"],
    description: "Introspective hip-hop production perfect for deep, lyrical content.",
  },
  {
    id: "10",
    title: "Afro Vibes",
    producer: "BEATVAULT",
    genre: "Afrobeats",
    bpm: 105,
    price: 32.99,
    mood: "Uplifting",
    coverUrl: cover2,
    duration: "3:48",
    plays: 11900,
    tags: ["Afro", "Dance", "Vibrant"],
    description: "Infectious Afrobeats groove with traditional percussion and modern production.",
  },
  {
    id: "11",
    title: "Future Bounce",
    producer: "BEATVAULT",
    genre: "Pop",
    bpm: 128,
    price: 21.99,
    mood: "Energetic",
    coverUrl: cover3,
    duration: "3:15",
    plays: 5600,
    tags: ["Pop", "Dance", "Radio"],
    description: "Radio-ready pop production with catchy hooks and energetic drops.",
  },
  {
    id: "12",
    title: "Dark Waters",
    producer: "BEATVAULT",
    genre: "Drill",
    bpm: 140,
    price: 31.99,
    mood: "Aggressive",
    isExclusive: true,
    coverUrl: cover4,
    duration: "3:25",
    plays: 18400,
    tags: ["Dark", "Drill", "Gritty"],
    description: "Atmospheric drill production with hypnotic melodies and hard-hitting 808s.",
  },
];

export const licenseOptions = [
  {
    id: "basic",
    name: "Basic",
    price: 0,
    description: "Non-profit use, up to 2,500 streams",
    features: ["MP3 file", "Credit required", "Non-profit only", "2,500 streams"],
  },
  {
    id: "premium",
    name: "Premium",
    price: 0,
    description: "Commercial use, up to 50,000 streams",
    features: ["WAV + MP3 files", "Credit required", "Commercial use", "50,000 streams"],
  },
  {
    id: "unlimited",
    name: "Unlimited",
    price: 50,
    description: "Unlimited commercial use",
    features: ["WAV + MP3 + Stems", "Credit optional", "Unlimited streams", "Radio & TV"],
    priceMultiplier: 2,
  },
  {
    id: "exclusive",
    name: "Exclusive",
    price: 200,
    description: "Full ownership transfer",
    features: ["All file formats", "No credit required", "Full ownership", "Removed from store"],
    priceMultiplier: 5,
  },
];
